03/07/2022 01:14:29 PM - validate_responses.py - INFO - Execution begins {current_dir:/scripts/aida/python, script_name:validate_responses.py, arguments:--log /output/logs/validate-responses.log --queries /data/user-queries --task task3 /scripts/aida/python/input/aux_data/log_specifications.txt /data/AUX-data/encoding_modality.txt /data/AUX-data/LDC2021E11.coredocs.txt /data/AUX-data/LDC2021E11.parent_children.tsv /data/AUX-data/LDC2021E11.sentence_boundaries.txt /data/AUX-data/LDC2021E11.image_boundaries.txt /data/AUX-data/LDC2021E11.keyframe_boundaries.txt /data/AUX-data/LDC2021E11.video_boundaries.txt example-task3-run-aws-2 /output/SPARQL-MERGED-output /output/SPARQL-VALID-output}
03/07/2022 01:14:29 PM - validate_responses.py - INFO - DEFAULT_INFO - validation started
03/07/2022 01:14:32 PM - validate_responses.py - ERROR - UNEXPECTED_CLAIM_VALUE - Unexpected subtopic 'Mask Regulations' for claim Condition5:CLL0C04C08B.000004:CLL0C04AJNP.001781 at /output/SPARQL-MERGED-output/Condition5/CLL0C04C08B.000004/CLL0C04AJNP.001781.ttl/AIDA_P3_TA3_OC_0001.rq.tsv:2
03/07/2022 01:14:32 PM - validate_responses.py - ERROR - UNEXPECTED_CLAIM_VALUE - Unexpected claimTemplate 'Wearing masks is required in location/GPE/facility-x' for claim Condition5:CLL0C04C08B.000004:CLL0C04AJNP.001781 at /output/SPARQL-MERGED-output/Condition5/CLL0C04C08B.000004/CLL0C04AJNP.001781.ttl/AIDA_P3_TA3_OC_0001.rq.tsv:2
03/07/2022 01:14:32 PM - validate_responses.py - WARNING - SPAN_OFF_BOUNDARY_CORRECTED - Correcting span '(0,0)-(0,0)' to '(1,0)-(5941,0)' because it is outside the boundary '(1,0)-(5941,0)' of document element 'L0C04ATJY' at /output/SPARQL-MERGED-output/Condition5/CLL0C04C08B.000004/CLL0C04AJNP.001781.ttl/AIDA_P3_TA3_GR_0001.rq.tsv:2
03/07/2022 01:14:32 PM - validate_responses.py - ERROR - UNKNOWN_CLAIM_ID - Unknown claim ID 'Condition5:CLL0C04C08B.000004:CLL0C04AJNP.001443' at /output/SPARQL-MERGED-output/Condition5/CLL0C04C08B.000004/CLL0C04C08B.000004.ranking.tsv:1
03/07/2022 01:14:32 PM - validate_responses.py - ERROR - UNEXPECTED_CLAIM_VALUE - Unexpected subtopic 'Mask Regulations' for claim Condition6:T302:CLL0C04AJNP.001833 at /output/SPARQL-MERGED-output/Condition6/T302/CLL0C04AJNP.001833.ttl/AIDA_P3_TA3_OC_0001.rq.tsv:2
03/07/2022 01:14:32 PM - validate_responses.py - ERROR - UNEXPECTED_CLAIM_VALUE - Unexpected claimTemplate 'Wearing masks is required in location/GPE/facility-x' for claim Condition6:T302:CLL0C04AJNP.001833 at /output/SPARQL-MERGED-output/Condition6/T302/CLL0C04AJNP.001833.ttl/AIDA_P3_TA3_OC_0001.rq.tsv:2
03/07/2022 01:14:32 PM - validate_responses.py - ERROR - UNEXPECTED_CLAIM_VALUE - Unexpected subtopic 'Mask Regulations' for claim Condition6:T302:CLL0C04AJNP.001443 at /output/SPARQL-MERGED-output/Condition6/T302/CLL0C04AJNP.001443.ttl/AIDA_P3_TA3_OC_0001.rq.tsv:2
03/07/2022 01:14:32 PM - validate_responses.py - ERROR - UNEXPECTED_CLAIM_VALUE - Unexpected claimTemplate 'Wearing masks is required in location/GPE/facility-x' for claim Condition6:T302:CLL0C04AJNP.001443 at /output/SPARQL-MERGED-output/Condition6/T302/CLL0C04AJNP.001443.ttl/AIDA_P3_TA3_OC_0001.rq.tsv:2
03/07/2022 01:14:32 PM - validate_responses.py - INFO - DEFAULT_INFO - validation finished (warnings:1, errors:7)
